# Generated by Django 2.2.5 on 2019-12-30 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_reference', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('subject_surname', models.CharField(blank=True, max_length=30, null=True)),
                ('group_ID', models.CharField(blank=True, max_length=30, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('seized_by', models.CharField(max_length=35)),
                ('seized_time', models.TimeField()),
                ('seized_date', models.DateField()),
                ('sub_location', models.CharField(max_length=80)),
                ('exhibit_reference', models.CharField(max_length=20)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('property_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.PropertyGroup')),
            ],
        ),
        migrations.CreateModel(
            name='StoredLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=80, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('property_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.PropertyItem')),
            ],
        ),
        migrations.CreateModel(
            name='SealNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seal_reference', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('property_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.PropertyItem')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='add image')),
                ('image_number', models.CharField(blank=True, max_length=5, null=True)),
                ('property_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.PropertyItem')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.CharField(blank=True, max_length=10, null=True)),
                ('house_number', models.CharField(blank=True, max_length=10, null=True)),
                ('house_name', models.CharField(blank=True, max_length=50, null=True)),
                ('road_name', models.CharField(blank=True, max_length=80, null=True)),
                ('town', models.CharField(blank=True, max_length=80, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('property_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.PropertyItem')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=35, null=True)),
                ('first_name', models.CharField(blank=True, max_length=35, null=True)),
                ('last_name', models.CharField(blank=True, max_length=35, null=True)),
                ('date_of_birth', models.DateField(blank=True, max_length=35, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('property_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.PropertyItem')),
            ],
        ),
        migrations.CreateModel(
            name='FoundLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_one', models.CharField(blank=True, max_length=80, null=True)),
                ('word_two', models.CharField(blank=True, max_length=80, null=True)),
                ('word_three', models.CharField(blank=True, max_length=80, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('property_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.PropertyGroup')),
            ],
        ),
        migrations.CreateModel(
            name='FoundAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.CharField(blank=True, max_length=10, null=True)),
                ('house_number', models.CharField(blank=True, max_length=10, null=True)),
                ('house_name', models.CharField(blank=True, max_length=50, null=True)),
                ('road_name', models.CharField(blank=True, max_length=80, null=True)),
                ('town', models.CharField(blank=True, max_length=80, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('property_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.PropertyGroup')),
            ],
        ),
    ]
